### ISSUE TITLE
Aircraft out of sync

### ISSUE THREAD

**Issue by LandonPatmore** [Sequal32/yourcontrol#6] opened 2020-09-06 17:15 UTC
Friend and I tried this plugin out, we have used SmartCopilot so we have experience with this.  We were on version `1.2.2`.

Both aircraft:

- TBM
- Turned off
- Both a KSEA
- Ramp 184

I turned my server on and he connected.  Instantly, his plane turned on and mine stayed off even though we did not manipulate switches inside the aircraft.  My friend then pulled the crash bar down to shut all electrical systems off and then my plane turned on.

We tried pausing, and reloading, yet the issue persisted.

**Comment by Sequal32** [comment] 2020-09-06 17:42
Thanks for this! Seems like it was caused by bad simulation variables in SimConnect. The battery was being read as true/false when the aircraft state does not reflect this. This will be fixed in the next release!

Did you also try flying around? If so did that go smoothly?

**Comment by LandonPatmore** [comment] 2020-09-06 17:44
Since the TBM has 3 positions: OFF, BATT, and GEN, bools don't work in this instance.  Is this a limitation of simconnect?

We could not fly since one plane was shut off while the other was on sadly :/

**Comment by Sequal32** [comment] 2020-09-06 17:46
Yeah SimConnect unfortunately doesn't have simulation variables for multi state batteries. A new release has been published, let me know how that goes!

**Closed by Sequal32** 2020-09-06 17:46 UTC

**Comment by LandonPatmore** [comment] 2020-09-06 17:48
Good job microsoft...

Will try later when my buddy gets on, thanks!

**Comment by Sequal32** [comment] 2020-09-06 18:05
FYI I forgot to include something so if you downloaded the release prior to this message you should get it again ;)
